version: "3.8"

services:
  pixoo-wall:
    image: mrorbitman/pixoo-wall:latest
    container_name: pixoo-wall
    environment:
      - PIXOO_IP=${PIXOO_IP}
      - AATA_API_KEY=${AATA_API_KEY}
      - AWS_REGION=${AWS_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - SLEEP_DURATION=${SLEEP_DURATION:-60}
    restart: unless-stopped
