name: restore_install_cache
description: restores node_modules from the cache and fails if no cache entry found
runs:
  using: composite
  steps:
    # restore node_modules from cache
    - uses: actions/cache@v4
      id: npm-cache
      with:
        path: |
          node_modules
          packages/**/node_modules
        key: ${{ runner.os }}-${{ hashFiles('package-lock.json') }}
        fail-on-cache-miss: true
